### ISSUE TITLE
I have a problem running this package, can you tell me what the problem is?

### ISSUE THREAD

**Issue by Knushm** [jackarivera/cerulean_sonar#2]
environment
Ubuntu20.04
ros2 : foxy
python version 3.8.10

<problem>
Traceback (most recent call last):
File "/home/furo/colcon_ws/install/cerulean_sonar/lib/cerulean_sonar/sonar_node", line 11, in <module>
load_entry_point('cerulean-sonar', 'console_scripts', 'sonar_node')()
File "/home/furo/colcon_ws/build/cerulean_sonar/cerulean_sonar/sonar_node.py", line 68, in main
rclpy.spin(node)
File "/opt/ros/foxy/lib/python3.8/site-packages/rclpy/init.py", line 187, in spin
executor = get_global_executor() if executor is None else executor
File "/opt/ros/foxy/lib/python3.8/site-packages/rclpy/init.py", line 84, in get_global_executor
__executor = SingleThreadedExecutor()
File "/opt/ros/foxy/lib/python3.8/site-packages/rclpy/executors.py", line 707, in init
super().init(context=context)
File "/opt/ros/foxy/lib/python3.8/site-packages/rclpy/executors.py", line 168, in init
self._guard = GuardCondition(
File "/opt/ros/foxy/lib/python3.8/site-packages/rclpy/guard_condition.py", line 25, in init
self.__handle = Handle(_rclpy.rclpy_create_guard_condition(capsule))
_rclpy.RCLError: Failed to create guard_condition: the given context is not valid, either rcl_init() was not called or rcl_shutdown() was called., at /tmp/binarydeb/ros-foxy-rcl-1.1.14/src/rcl/guard_condition.c:67
Exception ignored in: <function Executor.del at 0x7f4dc8088f70>
Traceback (most recent call last):
File "/opt/ros/foxy/lib/python3.8/site-packages/rclpy/executors.py", line 239, in del
if self._sigint_gc is not None:
AttributeError: 'SingleThreadedExecutor' object has no attribute '_sigint_gc'

I tried to solve this problem but couldn't solve it.
Any help would be appreciated.

**Comment by jackarivera** [comment]
Could you try this package: https://github.com/CeruleanSonar/s500_ros2

I updated this package and tested it properly in that repository. This package should be archived.
If you are still getting the same issue or any other issues please post them there and I will try and see if I can reproduce them.
